import { defineConfig } from "@playwright/test";
export default defineConfig({
  testDir: "tests",
  testMatch: [
    "demo.spec.ts",
    "timer-face.spec.ts",
    "browser.spec.ts",
    "camera.spec.ts",
    "wire-selection.spec.ts",
    "wire-ui.spec.ts",
    "wire-controls.spec.ts",
    "wire-inspector.spec.ts",
    "wire-sharp-bends.spec.ts",
    "palette-colors.spec.ts",
    "wire-relocation.spec.ts",
    "hud.spec.ts",
    "persistence.spec.ts",
    "materials.spec.ts",
    "logic.spec.ts", "logic-interaction.spec.ts", "wires.spec.ts", "lighting.spec.ts", "lighting-walk.spec.ts",
    "walk.spec.ts",
    "plots.spec.ts",
    "selection.spec.ts",
    "precision.spec.ts",
    "gizmo.spec.ts",
    "overlap.spec.ts",
    "paths.spec.ts",
  ],
  timeout: 40000,
  workers: 1,
  webServer: {
    command: "npm run dev",
    url: "http://127.0.0.1:5178",
    reuseExistingServer: true,
    timeout: 30000,
  },
  use: {
    channel: "chrome",
    headless: true,
    viewport: { width: 1440, height: 960 },
    baseURL: "http://127.0.0.1:5178",
    screenshot: "only-on-failure",
  },
  reporter: "list",
});

