import {chromium} from '@playwright/test';
import {writeFileSync} from 'node:fs';
const browser=await chromium.launch({channel:'chrome',headless:true});
const target=process.env.TIMBER_URL||'http://127.0.0.1:5179/';
const prefix=process.env.TIMBER_ARTIFACT_PREFIX||'package';
if(!/^[a-z-]+$/.test(prefix))throw new Error('Invalid artifact prefix');
const page=await browser.newPage({viewport:{width:1600,height:1000},deviceScaleFactor:1});const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('console',m=>{if(m.type()==='error')errors.push(m.text())});
const textureResponses=[];
page.on('response',r=>{if(r.url().includes('/textures/'))textureResponses.push({url:r.url(),status:r.status(),type:r.headers()['content-type']});});
await page.goto(target);await page.waitForFunction(()=>document.documentElement.dataset.ready==='true');await page.waitForTimeout(6500);
await page.screenshot({path:prefix==='package'?'artifacts/editor-desktop.png':`artifacts/${prefix}-desktop.png`});
const textureBase=new URL('textures/',target).href;
const texturesLoaded=textureResponses.length===9&&textureResponses.every(r=>r.url.startsWith(textureBase)&&r.status===200&&r.type?.startsWith('image/'));
const favicon=await page.locator('link[rel="icon"]').getAttribute('href');
const faviconResponse=await page.request.get(new URL(favicon,page.url()).href);
const faviconLoaded=faviconResponse.ok()&&faviconResponse.headers()['content-type']?.includes('image/svg+xml');
const initial={cards:await page.locator('.catalog-card').count(),pieces:await page.locator('#piece-count').textContent(),fps:await page.locator('#fps').textContent(),debugAPI:await page.evaluate(()=>typeof window.timber),collisionChecks:await page.locator('#overlap').count()===0};
await page.locator('#menu-tool').click();await page.locator('#new').click();await page.locator('#confirm-action').click();await page.locator('#build-tool').click();await page.locator('[data-item="smooth-wall"]').click();const b=await page.locator('#viewport>canvas').boundingBox();await page.mouse.click(b.x+b.width/2,b.y+b.height*.6);await page.waitForTimeout(1500);
const placed=await page.locator('#piece-count').textContent();await page.reload();await page.waitForFunction(()=>document.documentElement.dataset.ready==='true');const reloaded=await page.locator('#piece-count').textContent();
await page.setViewportSize({width:1024,height:768});await page.screenshot({path:prefix==='package'?'artifacts/editor-compact.png':`artifacts/${prefix}-compact.png`});const fits=await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth);
const oneStudControls=await page.locator('#nudge-buttons').getAttribute('aria-label')==='Move held placement by one stud' && await page.locator('#elevation,#build-mode,#path-fill').count()===0;
await page.locator('#land-tool').click();
const landSelector=await page.locator('[data-plot]').count()===25;
await page.locator('[data-plot="13"]').click();
const landExpansion=await page.locator('[data-plot="13"]').getAttribute('aria-pressed')==='true';
await page.locator('#close-modal').click();
await page.locator('#walk-tool').click();
const walkMode=await page.locator('#walk-tool').getAttribute('aria-pressed')==='true' && (await page.locator('#camera-hint').textContent()).includes('Jump');
await page.keyboard.press('c');
const freeMode=await page.locator('#walk-tool').getAttribute('aria-pressed')==='false';
const result={target,errors,texturesLoaded,faviconLoaded,oneStudControls,landSelector,landExpansion,walkMode,freeMode,initial,placed,reloaded,compactFits:fits};writeFileSync(`artifacts/${prefix}-check.json`,JSON.stringify(result,null,2));console.log(JSON.stringify(result,null,2));await browser.close();if(!texturesLoaded||!faviconLoaded||!landSelector||!landExpansion||!walkMode||!freeMode||!oneStudControls||errors.length||initial.cards!==102||!initial.collisionChecks||placed!=='1 pieces'||reloaded!=='1 pieces'||!fits)process.exitCode=1;
